### PR TITLE
Update generator to do less modification on newer provider

### PR DESCRIPTION
**Pull request by Lorac**
I updated the generator to reflect the changes I made when I created my project with the generator. It should be less work after generating the project using these modifications.

### CODE REVIEW

**Comment by kevinchalet** [comment]
Wooops, for some reasons, I missed this PR.

@jerriep PTAL. Looks like the .xproj file should also be updated.

**Comment by Lorac** [comment]
@PinpointTownes Updated the .xproj

**Comment by jerriep** [comment]
I will take a look as soon as I have time... may take a few days though

**Comment by kevinchalet** [comment]
@Lorac looks fine, thanks. If you want to squash your PR, please do it.

I'll merge your PR tomorrow.

**Comment by Lorac** [comment]
@PinpointTownes squashed

**Comment by kevinchalet** [comment]
@Lorac thanks!

Merged and pushed to NPM.

https://github.com/aspnet-contrib/generator-aspnet-oauth/commit/ce40d439c891b4c5e71289588192aa6f79aa1527

**Pull request closed without merging**
