### PR TITLE
React to API/naming changes in aspnet/Security

### PR DESCRIPTION
**Pull request by kevinchalet**
@jerriep please review and merge when you have time :+1: 

To merge, please use cherry picking:

```
git remote add pinpoint https://github.com/PinpointTownes/generator-aspnet-oauth.git
git fetch pinpoint
git cherry-pick 8e309a5cf7379a50e24929199f59cdb2e4df7a23
git push
```

### CODE REVIEW

**Comment by jerriep** [comment]
Is cherry picking the only way to get a clean commit history?

**Comment by kevinchalet** [comment]
If you want to keep both the author and the committer of a commit (like in the following screenshot) cherry picking is the easiest way to go:

image

The good old `git merge fork/branch --ff-only` is great, but it doesn't track the real committer of the commit, so I only use it when I want to merge my own PRs.

**Comment by kevinchalet** [comment]
Ping @jerriep :smile:

**Comment by jerriep** [comment]
Sorry, was supposed to do it on Friday, but then I went to Kuala Lumpur for a few days and it never got done. 

It is published now...

**Comment by kevinchalet** [comment]
Thanks! (and congratulations for your first cherry-picked commit :tada:)

**Pull request closed without merging**
