### PR TITLE
Fixes generator initialization. Closes #8

### LINKED ISSUE #8: Issue running generator
Any tips as to where I should begin to look with the following error?

? 'Allo Andy! What would you like to do? Aspnet Oauth

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo aspnet-oauth

? What is the name of the provider you want to create? xxxxpb03
? What is your name? xxxx3
? What is the Authorization Endpoint for this service? https://xxxx.com/auth
? What is the Token Endpoint for this service? https://xxxx.com/token
? What is the User Information Endpoint for this service? https://xxxx.com/info

```
 _-----_
|       |    .-----------------------.
|--(o)--|    |      Bye from us!     |
```

   `---------´   |       Chat soon.      |
    ( _´U`_ )    |      Yeoman team      |
    /**_A**_\    |    http://yeoman.io   |
     |  ~  |     '-----------------------'
   **'._**.'__
 ´   `|° ´ Y`

readline.js:924
            throw err;
            ^

TypeError: Cannot set property 'name' of undefined
    at null.<anonymous> (C:\Users\andy\AppData\Roaming\npm\node_modules\generator-aspnet-oauth\generators\app\index.js:48:30)
    at null.<anonymous> (C:\Users\andy\AppData\Roaming\npm\node_modules\generator-aspnet-oauth\node_modules\yeoman-generator\lib\base.js:226:7)
    at PromptUI.onCompletion (C:\Users\andy\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\lib\ui\prompt.js:57:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (C:\Users\andy\AppData\Roaming\npm\node_modules\yo\node_modules\rx-lite\rx.lite.js:1550:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\andy\AppData\Roaming\npm\node_modules\yo\node_modules\rx-lite\rx.lite.js:1489:14)
    at Subject.Rx.Subject.addProperties.onCompleted (C:\Users\andy\AppData\Roaming\npm\node_modules\yo\node_modules\rx-lite\rx.lite.js:5871:19)
    at Subject.tryCatcher (C:\Users\andy\AppData\Roaming\npm\node_modules\yo\node_modules\rx-lite\rx.lite.js:63:31)
    at AutoDetachObserverPrototype.completed (C:\Users\andy\AppData\Roaming\npm\node_modules\yo\node_modules\rx-lite\rx.lite.js:5796:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\andy\AppData\Roaming\npm\node_modules\yo\node_modules\rx-lite\rx.lite.js:1489:14)
    at AutoDetachObserver.tryCatcher (C:\Users\andy\AppData\Roaming\npm\node_modules\yo\node_modules\rx-lite\rx.lite.js:63:31)

### PR DESCRIPTION
**Pull request by jerriep**

### CODE REVIEW

**Comment by kevinchalet** [comment]
Thanks, Jerrie!

Curious: was this bug caused by a breaking change in yeoman?

https://github.com/aspnet-contrib/generator-aspnet-oauth/commit/6750989fdb93e7aee6998962ab1931b3d89c33b8

**Comment by jerriep** [comment]
Seems the `init` method was not called. It was looking for an `initializing` method instead. I could not find any documentation about this change. The Yeoman documentation (http://yeoman.io/authoring/running-context.html) list it under the priorities as `initializing` but one of their own samples shows it as `init`.

The `init` method used to work since I initially created the generator, so I am not sure when this changed. Strange thing is however that the aspnet generator also uses `init` (https://github.com/OmniSharp/generator-aspnet/blob/master/app/index.js#L21-L24) and their seems to work.

It is all very confusing to me... :(

@PinpointTownes also remember to merge (or cherry pick) the PR please

**Comment by kevinchalet** [comment]
Thanks for the explanation! :clap: 

I cherry-picked your PR before commenting. Here's the resulting commit: https://github.com/aspnet-contrib/generator-aspnet-oauth/commit/6750989fdb93e7aee6998962ab1931b3d89c33b8

**Comment by jerriep** [comment]
Oh sorry :blush: I just saw the "Closed with unmerged commits" message and did not look further... Thanks

**Comment by kevinchalet** [comment]
Hehe yeah, that's the downside of using cherry-picking :smile:

**Pull request closed without merging**
