### PR TITLE
React to API changes in aspnet/Security

### PR DESCRIPTION
**Pull request by kevinchalet**
https://github.com/aspnet/Security/commit/081577e4f4996082a4fc28ef77c84f54c7d04183
https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/610aba158db9fd20ff3046437740e55d9e37cf87

@jerriep please review this PR when you can :family:

### CODE REVIEW

**Comment by jerriep** [comment]
Sure, will check tomorrow...

**Comment by kevinchalet** [comment]
Thanks Jerrie! (merged: https://github.com/aspnet-contrib/generator-aspnet-oauth/commit/58bdf658cd8db7bfb7ad89dd37659e572c1a24bb)

**Comment by jerriep** [comment]
Haha, yeah but I have the stupid "merge" commit again! I mess it up everytime... :(

**Comment by kevinchalet** [comment]
Hehe, don't worry, I rewrote the git history to get rid of this annoying merge commit :+1:

**Comment by jerriep** [comment]
:smile: :+1:

**Pull request merged**
